version: '3.7'

services:
  front-end:
    container_name: react_container
    restart: always
    build:
      context: mainClient
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  back-end:
    container_name: golang_container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    build:
      context: mainServer
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./gitfiles:/gitfiles
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: AlexandriaPG
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data