host: localhost:8080
info:
  contact: {}
  description: Documentation of Alexandria's API. Has not been generated yet, view the project README.md for instructions
    in this interactive documentation.
  title: API documentation
  version: 1.0.0
paths: {}
swagger: "2.0"
