definitions:
  controllers.Joke:
    properties:
      id:
        type: integer
      joke:
        type: string
      likes:
        type: integer
    required:
    - id
    - joke
    type: object
host: localhost:8080
info:
  contact:
    name: TUDelft Software Project 2022
  description: Documentation of Alexandria's API
  title: API documentation
  version: 1.0.0
paths:
  /helloWorldJson:
    get:
      description: Returns a joke in JSON format
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Joke'
            type: array
      summary: Get hello world
swagger: "2.0"
