host: localhost:8080
info:
  contact: {}
  description: Documentation of Alexandria's API. Endpoints can be tried out directly
    in this interactive documentation.
  title: API documentation
  version: 1.0.0
paths:
  /articles/{articleID}/versions/{versionID}:
    put:
      consumes:
      - multipart/form-data
      description: Upload files to update an article version, can only be done by
        an owner.
      parameters:
      - description: Article ID
        in: path
        name: articleID
        required: true
        type: string
      - description: Version ID
        in: path
        name: versionID
        required: true
        type: string
      responses:
        "200":
          description: ""
        "400":
          description: ""
        "404":
          description: ""
      summary: Update article version
swagger: "2.0"
