host: localhost:8080
info:
  contact: {}
  description: Documentation of Alexandria's API. Endpoints can be tried out directly
    in this interactive documentation.
  title: API documentation
  version: 1.0.0
paths:
  /articles/{articleID}/versions/{versionID}:
    post:
      consumes:
      - multipart/form-data
      description: Upload files to update an article version, can only be done by
        an owner. Requires multipart form data, with a file attached as the field
        "file"
      parameters:
      - description: Article ID
        in: path
        name: articleID
        required: true
        type: string
      - description: Version ID
        in: path
        name: versionID
        required: true
        type: string
      responses:
        "200":
          description: Success
        "400":
          description: Bad request, possibly bad file data or permissions
        "404":
          description: Specified article version not found
      summary: Update article version
swagger: "2.0"
